/*******************************************************************************
* File Name: cycfg_connectivity.h
*
* Description:
* Establishes all necessary connections between hardware elements.
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_CONNECTIVITY_H)
#define CYCFG_CONNECTIVITY_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "notices.h"
void init_connectivity(void);

#define Blue_HSIOM P11_1_TCPWM0_LINE_COMPL1
#define EZI2C_SCL_HSIOM P6_0_SCB3_I2C_SCL
#define EZI2C_SDA_HSIOM P6_1_SCB3_I2C_SDA
#define ioss_0__port_6__pin_4__HSIOM P6_4_CPUSS_SWJ_SWO_TDO
#define ioss_0__port_6__pin_6__HSIOM P6_6_CPUSS_SWJ_SWDIO_TMS
#define ioss_0__port_6__pin_7__HSIOM P6_7_CPUSS_SWJ_SWCLK_TCLK

#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_CONNECTIVITY_H */
