/*******************************************************************************
* File Name: cycfg_capsense.c
* Version: 1.0
*
* Description:
* CapSense middleware configuration
* This file should not be modified. It was automatically generated by
* CapSense Configurator 1.0.0 build 592
*
********************************************************************************
* Copyright (c) 2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "cycfg_capsense.h"
#include "cy_capsense_structure.h"
#include "cy_capsense_config.h"

/*******************************************************************************
* Defines the RAM Data Structure variables and their init data in flash
*******************************************************************************/

/**
* The variable that contains the CapSense configuration, settings and
* scanning results. cy_capsense_dsRam represents RAM Data Structure.
*/
cy_stc_capsense_ram_t cy_capsense_dsRam;

#if (0u != CY_CAPSENSE_ON_DEBOUNCE_EN)
/*******************************************************************************
* Declares Widget's De-bounce Counters
*******************************************************************************/
static cy_stc_capsense_debounce_list_t cy_capsense_debounce;
#endif

#if (0u != (CY_CAPSENSE_CSD_AUTOTUNE & CY_CAPSENSE_CSD_SS_TH_EN))
/***************************************************************************//**
* Declares Noise Envelope data structures
*******************************************************************************/
static cy_stc_capsense_smartsense_csd_noise_envelope_list_t cy_capsense_noiseEnvelope;
#endif

#if (0u != CY_CAPSENSE_DIPLEXING_EN)
static const cy_capsense_diplex_table_t cy_capsense_diplexTable =
{
};
#endif

#if (0u != CY_CAPSENSE_CSX_TOUCHPAD_WIDGET_EN)
/***************************************************************************//**
* Declares CSX Touchpad data
*******************************************************************************/
static cy_stc_capsense_touchpad_data_list_t cy_capsense_csxTouchpadData;
#endif

/***************************************************************************//**
* Declares Filter History Objects
*******************************************************************************/
static cy_stc_capsense_fltr_history_list_t cy_capsense_fltrHistory;

#if ((0u != CY_CAPSENSE_REGULAR_RC_ALP_FILTER_EN) || \
     (0u != CY_CAPSENSE_PROX_RC_ALP_FILTER_EN))
/***************************************************************************//**
* Declares ALP Filter History Objects
*******************************************************************************/
static cy_stc_capsense_alp_fltr_history_list_t cy_capsense_alpFltrHistory;
#endif

/***************************************************************************//**
* Centroid positions history
*******************************************************************************/
static cy_stc_capsense_pos_history_list_t cy_capsense_posHistory;

/*******************************************************************************
* Defines and initializes the Flash Data Structure
*******************************************************************************/

/**
* Constant for the FLASH Data Structure
*/
const cy_stc_capsense_flash_t cy_capsense_dsFlash =
{
    /* Flash Widget Initialization Data */
    {
        { /* Button0 */
            .ptr2SnsFlash = &cy_capsense_ioList[0u],
            .ptr2WdgtRam = (void *)&cy_capsense_dsRam.wdgtList.button0,
            .ptr2SnsRam = cy_capsense_dsRam.snsList.button0,
            .ptr2FltrHistory = (void *)cy_capsense_fltrHistory.button0,
            .ptr2DebounceArr = cy_capsense_debounce.button0,
            .staticConfig = (0x1),
            .totalNumSns = 1u,
            .wdgtType = (uint8_t)CY_CAPSENSE_WD_BUTTON_E,
            .senseMethod = (uint8_t)CY_CAPSENSE_SENSE_METHOD_CSX_E,
            .numCols = 1u,
            .numRows = 1u,
            .xResolution = 0u,
            .yResolution = 0u,
            .xCentroidMultiplier = (0u),
            .yCentroidMultiplier = (0u),
            .ptr2NoiseEnvlp = (cy_stc_capsense_smartsense_csd_noise_envelope_t *)0u,
            .ptr2DiplexTable = (const uint8_t *)0u,
            .ptr2CsxTouchpad = (cy_stc_capsense_touchpad_data_t *)0u,
            .ptr2PosHistory = (void *)0u,
            .iirFilterCoeff = 128u,
        },
        { /* LinearSlider0 */
            .ptr2SnsFlash = &cy_capsense_ioList[2u],
            .ptr2WdgtRam = (void *)&cy_capsense_dsRam.wdgtList.linearslider0,
            .ptr2SnsRam = cy_capsense_dsRam.snsList.linearslider0,
            .ptr2FltrHistory = (void *)cy_capsense_fltrHistory.linearslider0,
            .ptr2DebounceArr = cy_capsense_debounce.linearslider0,
            .staticConfig = (0x11),
            .totalNumSns = 5u,
            .wdgtType = (uint8_t)CY_CAPSENSE_WD_LINEAR_SLIDER_E,
            .senseMethod = (uint8_t)CY_CAPSENSE_SENSE_METHOD_CSD_E,
            .numCols = 5u,
            .numRows = 0u,
            .xResolution = 100,
            .yResolution = 0u,
            .xCentroidMultiplier = 6400,
            .yCentroidMultiplier = (0u),
            .ptr2NoiseEnvlp = cy_capsense_noiseEnvelope.linearslider0,
            .ptr2DiplexTable = (const uint8_t *)0u,
            .ptr2CsxTouchpad = (cy_stc_capsense_touchpad_data_t *)0u,
            .ptr2PosHistory = (void *)&cy_capsense_posHistory.linearslider0,
            .iirFilterCoeff = 128u,
        },
    },

    /* Flash Sensor Initialization Data */
};

/**
* The array of the pointers to the electrode specific register.
*/
const cy_stc_capsense_flash_io_t cy_capsense_ioList[CY_CAPSENSE_TOTAL_ELECTRODES] =
{
    { /* Button0_Rx0 */
        CY_CAPSENSE_BUTTON0_RX0_PORT,
        CY_CAPSENSE_BUTTON0_RX0_PIN,
    },
    { /* Button0_Tx */
        CY_CAPSENSE_BUTTON0_TX_PORT,
        CY_CAPSENSE_BUTTON0_TX_PIN,
    },
    { /* LinearSlider0_Sns0 */
        CY_CAPSENSE_LINEARSLIDER0_SNS0_PORT,
        CY_CAPSENSE_LINEARSLIDER0_SNS0_PIN,
    },
    { /* LinearSlider0_Sns1 */
        CY_CAPSENSE_LINEARSLIDER0_SNS1_PORT,
        CY_CAPSENSE_LINEARSLIDER0_SNS1_PIN,
    },
    { /* LinearSlider0_Sns2 */
        CY_CAPSENSE_LINEARSLIDER0_SNS2_PORT,
        CY_CAPSENSE_LINEARSLIDER0_SNS2_PIN,
    },
    { /* LinearSlider0_Sns3 */
        CY_CAPSENSE_LINEARSLIDER0_SNS3_PORT,
        CY_CAPSENSE_LINEARSLIDER0_SNS3_PIN,
    },
    { /* LinearSlider0_Sns4 */
        CY_CAPSENSE_LINEARSLIDER0_SNS4_PORT,
        CY_CAPSENSE_LINEARSLIDER0_SNS4_PIN,
    },
};

#if ((0u != CY_CAPSENSE_CSD_EN) && (0u != CY_CAPSENSE_CSD_SHIELD_EN) && \
     (CY_CAPSENSE_CSD_TOTAL_SHIELD_COUNT > 0u))
/**
 *  The array of the pointers to the shield electrode specific register.
 */
const cy_stc_capsense_flash_io_t cy_capsense_shieldIoList[CY_CAPSENSE_CSD_TOTAL_SHIELD_COUNT] =
{
};
#endif /* #if ((0u != CY_CAPSENSE_CSD_EN) && (0u != CY_CAPSENSE_CSD_SHIELD_EN) &&
     (CY_CAPSENSE_CSD_TOTAL_SHIELD_COUNT > 0u)) */

/* Initialization data for RAM widget list */
const cy_stc_capsense_ram_wd_list_t cy_capsense_ramWidgetInit =
{
    .button0 = {
        .resolution = 100,
        .fingerTh = 90,
        .noiseTh = 40,
        .nNoiseTh = 40,
        .hysteresis = 20,
        .onDebounce = 3,
        .lowBslnRst = 30,
        .bslnCoeff = 0,
        .idacMod = {32},
        .rowIdacMod = {32},
        .snsClk = 42,
        .rowSnsClk = 2,
        .snsClkSource = 0u,
        .rowSnsClkSource = 0u,
        .fingerCap = 300,
        .sigPFC = 0,
    },
    .linearslider0 = {
        .resolution = 12,
        .fingerTh = 100,
        .noiseTh = 40,
        .nNoiseTh = 40,
        .hysteresis = 10,
        .onDebounce = 3,
        .lowBslnRst = 30,
        .bslnCoeff = 0,
        .idacMod = {32},
        .rowIdacMod = {32},
        .snsClk = 4,
        .rowSnsClk = 2,
        .snsClkSource = 0u,
        .rowSnsClkSource = 0u,
        .fingerCap = 100,
        .sigPFC = 0,
        .position = {0},
    },
};

/* IDAC Initialization Data */
const uint8_t cy_capsense_ramIdacInit[CY_CAPSENSE_TOTAL_SENSORS * CY_CAPSENSE_NUM_SCAN_FREQS] =
{
    /* Button0 */
    32,
    /* LinearSlider0 */
    32,32,32,32,32,
};

/* [] END OF FILE */

