/*******************************************************************************
* File Name: cycfg_pins.h
*
* Description:
* Pin configuration
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_PINS_H)
#define CYCFG_PINS_H

#include "notices.h"
#include "cy_gpio.h"
#include "cycfg_connectivity.h"

#if defined(__cplusplus)
extern "C" {
#endif

#define Red_PORT GPIO_PRT0
#define Red_PIN 3U
#define Red_NUM 3U
#define Blue_PORT GPIO_PRT11
#define Blue_PIN 1U
#define Blue_NUM 1U
#define ioss_0__port_1__pin_0__PORT GPIO_PRT1
#define ioss_0__port_1__pin_0__PIN 0U
#define ioss_0__port_1__pin_0__NUM 0U
#define Green_PORT GPIO_PRT1
#define Green_PIN 1U
#define Green_NUM 1U
#define EZI2C_SCL_PORT GPIO_PRT6
#define EZI2C_SCL_PIN 0U
#define EZI2C_SCL_NUM 0U
#define EZI2C_SDA_PORT GPIO_PRT6
#define EZI2C_SDA_PIN 1U
#define EZI2C_SDA_NUM 1U
#define ioss_0__port_6__pin_4__PORT GPIO_PRT6
#define ioss_0__port_6__pin_4__PIN 4U
#define ioss_0__port_6__pin_4__NUM 4U
#define ioss_0__port_6__pin_6__PORT GPIO_PRT6
#define ioss_0__port_6__pin_6__PIN 6U
#define ioss_0__port_6__pin_6__NUM 6U
#define ioss_0__port_6__pin_7__PORT GPIO_PRT6
#define ioss_0__port_6__pin_7__PIN 7U
#define ioss_0__port_6__pin_7__NUM 7U
#define ioss_0__port_7__pin_1__PORT GPIO_PRT7
#define ioss_0__port_7__pin_1__PIN 1U
#define ioss_0__port_7__pin_1__NUM 1U
#define ioss_0__port_7__pin_2__PORT GPIO_PRT7
#define ioss_0__port_7__pin_2__PIN 2U
#define ioss_0__port_7__pin_2__NUM 2U
#define ioss_0__port_7__pin_5__PORT GPIO_PRT7
#define ioss_0__port_7__pin_5__PIN 5U
#define ioss_0__port_7__pin_5__NUM 5U
#define ioss_0__port_7__pin_7__PORT GPIO_PRT7
#define ioss_0__port_7__pin_7__PIN 7U
#define ioss_0__port_7__pin_7__NUM 7U
#define ioss_0__port_8__pin_1__PORT GPIO_PRT8
#define ioss_0__port_8__pin_1__PIN 1U
#define ioss_0__port_8__pin_1__NUM 1U
#define ioss_0__port_8__pin_2__PORT GPIO_PRT8
#define ioss_0__port_8__pin_2__PIN 2U
#define ioss_0__port_8__pin_2__NUM 2U
#define ioss_0__port_8__pin_3__PORT GPIO_PRT8
#define ioss_0__port_8__pin_3__PIN 3U
#define ioss_0__port_8__pin_3__NUM 3U
#define ioss_0__port_8__pin_4__PORT GPIO_PRT8
#define ioss_0__port_8__pin_4__PIN 4U
#define ioss_0__port_8__pin_4__NUM 4U
#define ioss_0__port_8__pin_5__PORT GPIO_PRT8
#define ioss_0__port_8__pin_5__PIN 5U
#define ioss_0__port_8__pin_5__NUM 5U
#define ioss_0__port_8__pin_6__PORT GPIO_PRT8
#define ioss_0__port_8__pin_6__PIN 6U
#define ioss_0__port_8__pin_6__NUM 6U
#define ioss_0__port_8__pin_7__PORT GPIO_PRT8
#define ioss_0__port_8__pin_7__PIN 7U
#define ioss_0__port_8__pin_7__NUM 7U

extern const cy_stc_gpio_pin_config_t Red_cfg;
extern const cy_stc_gpio_pin_config_t Blue_cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_1__pin_0__cfg;
extern const cy_stc_gpio_pin_config_t Green_cfg;
extern const cy_stc_gpio_pin_config_t EZI2C_SCL_cfg;
extern const cy_stc_gpio_pin_config_t EZI2C_SDA_cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_6__pin_4__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_6__pin_6__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_6__pin_7__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_7__pin_1__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_7__pin_2__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_7__pin_5__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_7__pin_7__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_8__pin_1__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_8__pin_2__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_8__pin_3__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_8__pin_4__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_8__pin_5__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_8__pin_6__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_8__pin_7__cfg;

void init_cycfg_pins(void);

#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_PINS_H */
