/***************************************************************************//**
* \file cy_capsense_config.h
* \version 0.7
*
* \brief
*  The CapSense configuration file.
*
********************************************************************************
* \copyright
* Copyright 2018, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#if !defined(CY_CAPSENSE_CONFIG_H)
#define CY_CAPSENSE_CONFIG_H

#include <stdint.h>
#include "cy_sysclk.h"
#include "cy_sysint.h"

/* The cycfg_peripherals.h file provides peripheral clock connectivity macros */
#include "cycfg_peripherals.h"

/* The cycfg_capsense.h file is generated by the CapSense configuration tool */
#include "cycfg_capsense.h"

#if defined(__cplusplus)
extern "C" {
#endif


/*
* Example of manual peripheral clock assignment
* #define CY_CAPSENSE_PERI_CLK_IDX   (X)
* #define CY_CAPSENSE_PERI_CLK_TYPE  (CY_SYSCLK_DIV_8_BIT)
*/


/*
 * Example of the Start Sample Callback assignment.
 * #define CY_CAPSENSE_START_SAMPLE_CALLBACK    (1u)
 * void Cy_CapSense_StartSampleCallback(cy_stc_active_sns_t *activeSensor);
 */


/*
 * Example of the Entry Callback assignment.
 * #define CY_CAPSENSE_ENTRY_CALLBACK           (1u)
 * void Cy_CapSense_EntryCallback(cy_stc_active_sns_t *activeSensor);
 */


/*
 * Example of the Exit Callback assignment.
 * #define CY_CAPSENSE_EXIT_CALLBACK            (1u)
 * void Cy_CapSense_ExitCallback(cy_stc_active_sns_t *activeSensor);
 */


/*
 * Example of the End Of Scan callback assignment.
 * #define CY_CAPSENSE_END_OF_SCAN_CALLBACK     (1u)
 * void Cy_CapSense_EndOfScanCallback(cy_stc_active_sns_t *activeSensor);
 */

#if !defined(CY_CAPSENSE_CPU_CLK_HZ)
#error "CPU clock frequency is not defined"
#endif

#if !defined(CY_CAPSENSE_PERI_CLK_HZ)
#error "Peripheral clock frequency is not defined"
#endif

#if !defined(CY_CAPSENSE_PERI_CLK_TYPE) || !defined(CY_CAPSENSE_PERI_CLK_IDX)
#error "Peripheral clock divider is not assigned"
#endif

__STATIC_INLINE void Cy_CapSense_SetClkDivider(uint32_t dividerValue)
{
    Cy_SysClk_PeriphSetDivider(CY_CAPSENSE_PERI_CLK_TYPE, CY_CAPSENSE_PERI_CLK_IDX, dividerValue);
}

/* Interrupt configuration structure defined at the application level */
extern const cy_stc_sysint_t CapSense_ISR_cfg;

#if defined(__cplusplus)
}
#endif

#endif /* End CY_CAPSENSE_CONFIG_H */


/* [] END OF FILE */
